---
- name: install system packages; latest versions
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - sudo
      - build-essential
      - tree
      - curl
      - wget
      - tmux
      - unzip
      - htop
      - less
      - dstat
      - dnsutils
      - iputils-ping

- name: remove dependencies that are no longer required
  apt:
    autoclean: yes

- name: allow sudo group passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL:ALL) NOPASSWD: ALL"

- name: create user account (defaults to developer); add to sudoers
  user:
    name: "{{ linux_base_user_name }}"
    state: present
    shell: /bin/bash
    create_home: yes
    group: root
    groups:
      - sudo
    append: yes

- name: get home folder of the 'developer' user
  shell: getent passwd "{{ linux_base_user_name }}" | cut -d":" -f6
  register: dev_user_home

- set_fact:
    linux_base_dev_user_home: "{{ dev_user_home.stdout }}"
    cacheable: yes